name: Deploy page

on:
  pull_request:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run check
      - run: npm run build
